module.exports = {
  apps: [
    {
      name: 'bobaxshop-bot',
      script: 'node_modules/.bin/tsx',
      args: 'apps/bot/src/index.ts',
      cwd: '/home/ubuntu/BotBobax',
      env_file: '/home/ubuntu/BotBobax/.env',
      restart_delay: 5000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      error_file: '/home/ubuntu/logs/bot-error.log',
      out_file: '/home/ubuntu/logs/bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'bobaxshop-web',
      script: 'node_modules/.bin/next',
      args: 'start',
      cwd: '/home/ubuntu/BotBobax/apps/web',
      env_file: '/home/ubuntu/BotBobax/.env',
      env: {
        PORT: 3000,
        NODE_ENV: 'production',
      },
      restart_delay: 5000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      error_file: '/home/ubuntu/logs/web-error.log',
      out_file: '/home/ubuntu/logs/web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
}
