module.exports = {
  apps: [
    {
      name: 'bobaxshop-bot',
      script: 'pnpm',
      args: '--filter bot dev',
      cwd: '/home/ubuntu/BotBobax',
      env_file: '/home/ubuntu/BotBobax/.env',
      restart_delay: 5000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      error_file: '/home/ubuntu/logs/bot-error.log',
      out_file: '/home/ubuntu/logs/bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'bobaxshop-web',
      script: 'pnpm',
      args: '--filter web dev',
      cwd: '/home/ubuntu/BotBobax',
      env_file: '/home/ubuntu/BotBobax/.env',
      env: {
        PORT: 3000,
      },
      restart_delay: 5000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      error_file: '/home/ubuntu/logs/web-error.log',
      out_file: '/home/ubuntu/logs/web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
}
